logo: /images/avatar.gif
han_type: zh-Hant
menu:
  Home: /
  归档: /pigeonhole
  Links: /links
  About: /about
disqus:
  short_name: YOUR_DISQUS_ID
duoshuo:
  short_name: YOUR_DUOSHUO_ID
icon:
  rss: /atom.xml
  facebook: YOUR_FACEBOOK_ID
  twitter: YOUR_TWITTER_ID
  github: YOUR_GITHUB_ID
  steam: YOUR_STEAM_PROFILE_ID
  weibo: YOUR_WEIBO_ID
  zhihu: YOUR_ZHIHU_ID

category_path: categories
tags_path: tags
show_post_tags: true
show_post_categories: true
