logo: /images/avatar.gif
favicon: images/favicon.png
han_type: zh-Hant
menu:
  Home: /
  归档: /pigeonhole
  Links: /links
  About: /about
disqus:
  short_name: YOUR_DISQUS_ID
duoshuo:
  short_name: YOUR_DUOSHUO_ID
icon:
  rss: /atom.xml
  facebook: YOUR_FACEBOOK_ID
  twitter: YOUR_TWITTER_ID
  github: YOUR_GITHUB_ID
  steam: YOUR_STEAM_PROFILE_ID
  weibo: YOUR_WEIBO_ID
  zhihu: YOUR_ZHIHU_ID
  xing:
  linkedin:

category_path: categories
tags_path: tags
show_post_tags: true
show_post_categories: true
show_home_post_tags: true
show_home_post_categories: true

googleanalytics:

backgrounds: "images/backgrounds/01.jpg,images/backgrounds/02.jpg,images/backgrounds/03.jpg,images/backgrounds/04.jpg"

footer_note: "All rights reserved. All logos and/or trademarks are property of their respective owners in the US and other countries."
